# Makefile for MinGW on Windows
CC = gcc
FC = g95
CXX = c:/wsjt-env/Qt5/Tools/mingw48_32/bin/g++

FFLAGS = -O2 -fbounds-check -Wall -Wno-precision-loss -fno-second-underscore
CFLAGS = -I. -fbounds-check

# Default rules
%.o: %.c
	${CC} ${CFLAGS} -c $<
%.o: %.f
	${FC} ${FFLAGS} -c $<
%.o: %.F
	${FC} ${FFLAGS} -c $<
%.o: %.f90
	${FC} ${FFLAGS} -c $<
%.o: %.F90
	${FC} ${FFLAGS} -c $<

all:    libm65.a m65.exe JT65code.exe mapsim.exe

OBJS1 = trimlist.o display.o getdphi.o pctile.o ccf65.o \
	decode1a.o sort.o filbig.o fil6521.o afc65b.o \
	twkfreq.o decode65b.o indexx.o ssort.o fchisq.o setup65.o \
	extract.o deep65.o ccf2.o demod64a.o chkhist.o graycode.o \
	interleave63.o unpackmsg.o encode65.o igray.o set.o unpackcall.o \
	unpackgrid.o grid2k.o unpacktext.o getpfx2.o packmsg.o \
	deg2grid.o packtext.o getpfx1.o packcall.o k2grid.o packgrid.o \
	wrapkarn.o nchar.o init_rs.o encode_rs.o decode_rs.o \
	wsjt_fft_compat.o rfile3a.o grid2deg.o pfxdump.o dpol.o \
	coord.o f77_wisdom.o gen65.o chkmsg.o ptt.o recvpkt.o symspec.o \
	iqcal.o iqfix.o timf2.o s3avg.o

libm65.a: $(OBJS1)
	ar cr libm65.a $(OBJS1) 
	ranlib libm65.a

OBJS3 = m65.o m65a.o map65a.o symspec.o decode0.o ftninit.o ftnquit.o \
	timer.o ipcomm.o sec_midn.o cutil.o 

LIBS3 = -L'C:/wsjt-env/Qt5/5.2.1/mingw48_32/lib' -lQt5Core

m65.exe: $(OBJS3) libm65.a
	$(CXX) -o m65.exe $(OBJS3) $(LIBS3) libm65.a ../libfftw3f_win.a \
	c:/MinGW/lib/libf95.a
	cp m65.exe ../../map65_install

OBJS2 = JT65code.o
JT65code.exe: $(OBJS2) libm65.a
	$(FC) -o JT65code.exe $(OBJS2) libm65.a

OBJS6 = mapsim.o cgen65.o noisegen.o gran.o
mapsim.exe: $(OBJS6) libm65.a
	$(FC) -o mapsim.exe $(OBJS6) libm65.a

INCPATH = -I'C:/wsjt-env/Qt5/5.2.1/mingw48_32/include/QtCore' \
	-I'C:/wsjt-env/Qt5/5.2.1/mingw48_32/include' 

ipcomm.o: ipcomm.cpp
	$(CXX) -c $(INCPATH) ipcomm.cpp

#m65a.o:	m65a.f90
#	$(FC) -c -fno-second-underscore -cpp m65a.f90

sec_midn.o: sec_midn.f90
	$(FC) -c -fno-second-underscore sec_midn.f90

#symspec.o: ../symspec.f90
#	$(FC) -c $(FFLAGS) -o symspec.o ../symspec.f90

OBJS5 = t1.o timer.o libm65.a
t1.exe: $(OBJS5)
	$(FC) $(FFLAGS) -o t1.exe $(OBJS5) libm65.a 

init_rs.o: init_rs.c
	$(CC) -c -DBIGSYM=1 -o init_rs.o init_rs.c

encode_rs.o: encode_rs.c
	$(CC) -c -DBIGSYM=1 -o encode_rs.o encode_rs.c

decode_rs.o: decode_rs.c
	$(CC) -c -DBIGSYM=1 -o decode_rs.o decode_rs.c

.PHONY : clean

clean:
	rm -f *.o libm65.a m65.exe jt65code.exe
